const B = require("./build");
const { Paragraph, TextRun, AlignmentType, HeadingLevel } = B;

function capitulo01() {
  return [
    B.chapterHeading(1, "El contrato de seguro de hogar: concepto, fuentes y principios"),

    B.p([B.italic("El seguro de hogar es, con diferencia, el ramo de daños más contratado en España y, a la vez, uno de los que genera mayor litigiosidad cotidiana: daños por agua, robos, incendios y reclamaciones de responsabilidad civil entre vecinos llenan cada año los juzgados de primera instancia y las mesas de los defensores del asegurado. Este primer capítulo sienta las bases conceptuales y normativas que sostienen todo lo que sigue.")]),

    B.h2("1.1. Concepto legal del contrato de seguro"),
    B.p("El punto de partida obligado es el artículo 1 de la Ley 50/1980, de 8 de octubre, de Contrato de Seguro (en adelante, LCS), que define la institución en términos que siguen plenamente vigentes:"),
    B.legalBox("Art. 1 LCS", "El contrato de seguro es aquel por el que el asegurador se obliga, mediante el cobro de una prima y para el caso de que se produzca el evento cuyo riesgo es objeto de cobertura, a indemnizar, dentro de los límites pactados, el daño producido al asegurado o a satisfacer un capital, una renta u otras prestaciones convenidas."),
    B.p("El seguro de hogar —también llamado seguro multirriesgo del hogar— es un seguro contra daños en sentido técnico: protege un interés patrimonial lícito (la integridad de la vivienda y sus enseres) frente a la realización de riesgos tipificados (incendio, agua, robo, fenómenos atmosféricos, etc.) y, además, incorpora de forma prácticamente universal una cobertura de responsabilidad civil de cabeza de familia, que muta su naturaleza parcial hacia el seguro de responsabilidad civil regulado en los artículos 73 y siguientes de la LCS. Esta doble naturaleza —seguro de daños propios y seguro de responsabilidad civil frente a terceros conviviendo en una misma póliza— es la primera clave de lectura que debe manejar cualquier profesional: cada siniestro debe reconducirse primero a su cobertura antes de analizar su régimen jurídico, porque las reglas de uno y otro bloque no son idénticas."),

    B.h2("1.2. Fuentes del régimen jurídico aplicable"),
    B.p("El seguro de hogar no se rige por una ley única. El profesional debe manejar, en la práctica, un entramado de fuentes que se articulan del siguiente modo:"),
    B.bullet([B.bold("Ley 50/1980, de Contrato de Seguro (LCS). "), B.run("Es la norma nuclear. Conforme a su artículo 2, sus preceptos tienen carácter imperativo salvo que la propia ley disponga otra cosa, si bien se admiten siempre las cláusulas contractuales más beneficiosas para el asegurado. Este carácter imperativo relativo —imperatividad a favor del asegurado— es una idea que reaparece constantemente en el resto del libro, por ejemplo al analizar la mora del asegurador (art. 20 LCS, capítulo 16) o el deber de declaración del riesgo (art. 10 LCS, capítulo 3).")]),
    B.bullet([B.bold("Código Civil. "), B.run("Rige con carácter supletorio las cuestiones generales de obligaciones y contratos (interpretación, nulidad, prescripción de acciones no específicamente reguladas, responsabilidad extracontractual del art. 1902 CC en su conexión con la cobertura de responsabilidad civil del hogar).")]),
    B.bullet([B.bold("Texto Refundido de la Ley General para la Defensa de los Consumidores y Usuarios (Real Decreto Legislativo 1/2007, TRLGDCU) y Ley 7/1998, de Condiciones Generales de la Contratación (LCGC). "), B.run("Aplicables porque el tomador de un seguro de hogar es, en la inmensa mayoría de los casos, un consumidor. Su régimen de cláusulas abusivas y control de incorporación se estudia en el capítulo 21, en diálogo permanente con el artículo 3 LCS que se aborda más adelante en este mismo capítulo.")]),
    B.bullet([B.bold("Real Decreto Legislativo 6/2004, de Ordenación y Supervisión de los Seguros Privados y su normativa de desarrollo, y el Texto Refundido de la Ley de Ordenación, Supervisión y Solvencia de las Entidades Aseguradoras y Reaseguradoras (Ley 20/2015, LOSSEAR). "), B.run("Regulan la solvencia y supervisión administrativa de las aseguradoras por la Dirección General de Seguros y Fondos de Pensiones (DGSFP), relevante para la vía de reclamación extrajudicial (capítulo 19).")]),
    B.bullet([B.bold("Real Decreto 300/2004, por el que se aprueba el Reglamento del Consorcio de Compensación de Seguros, y su normativa reguladora. "), B.run("Determinante en la cobertura de riesgos extraordinarios (inundaciones, terremotos, tempestad ciclónica atípica) que en la práctica excluyen las condiciones generales de las pólizas privadas y que asume el Consorcio con su propio baremo (capítulo 8).")]),
    B.bullet([B.bold("Ley 5/2019 y normativa hipotecaria conexa, Ley de Propiedad Horizontal (Ley 49/1960) y Código Técnico de la Edificación. "), B.run("Inciden, respectivamente, en el seguro de hogar vinculado a préstamo hipotecario, en la interacción entre el seguro individual del piso y el seguro de comunidad, y en los estándares constructivos relevantes para la causa de determinados siniestros de agua o de estructura.")]),

    B.h2("1.3. Caracteres jurídicos del contrato de seguro de hogar"),
    B.p("De la definición legal y de la práctica aseguradora se extraen los caracteres que, en cada capítulo, condicionan la solución de los casos:"),
    B.bullet([B.bold("Bilateral y sinalagmático: "), B.run("genera obligaciones recíprocas (pago de la prima frente a cobertura del riesgo).")]),
    B.bullet([B.bold("Oneroso y aleatorio: "), B.run("la prestación del asegurador depende de un evento incierto (el siniestro), lo que justifica el rigor con el que la ley trata el deber de declaración del riesgo (art. 10 LCS) y las causas de exoneración por dolo o culpa grave (arts. 19 y 48 LCS).")]),
    B.bullet([B.bold("De buena fe reforzada (uberrimae fidei): "), B.run("la asimetría de información entre tomador y asegurador exige un estándar de lealtad recíproca superior al de los contratos comunes; de ahí derivan tanto los deberes del tomador (declaración del riesgo, comunicación del siniestro) como los del asegurador (transparencia, claridad de las condiciones ex art. 3 LCS).")]),
    B.bullet([B.bold("De adhesión: "), B.run("las condiciones generales las redacta unilateralmente el asegurador; el tomador se limita a aceptarlas. Este carácter es el que activa los controles de incorporación y transparencia que se explican en el epígrafe 1.5.")]),
    B.bullet([B.bold("Indemnizatorio: "), B.run("en el seguro de daños rige el llamado principio indemnizatorio, que impide que el asegurado obtenga, a través del seguro, un enriquecimiento superior al daño realmente sufrido; de él derivan tanto la regla proporcional del infraseguro (art. 30 LCS, capítulo 15) como el derecho de subrogación del asegurador frente a terceros responsables (art. 43 LCS).")]),

    B.h2("1.4. El seguro multirriesgo del hogar: continente y contenido"),
    B.p("Aunque la LCS no emplea estos términos, la práctica aseguradora española distingue de forma constante entre:"),
    B.bullet([B.bold("El continente: "), B.run("la construcción en sí —muros, techos, suelos, instalaciones fijas, elementos empotrados, e incluso, según póliza, anejos como garaje o trastero— y, en su caso, los elementos comunes en la proporción de la cuota de participación cuando el asegurado es propietario y la comunidad carece de seguro propio o el suyo es insuficiente.")]),
    B.bullet([B.bold("El contenido: "), B.run("los bienes muebles del hogar: mobiliario, electrodomésticos, ropa, y, con límites cuantitativos específicos que conviene revisar en cada póliza, joyas, dinero en efectivo, obras de arte y objetos de especial valor.")]),
    B.p("Esta distinción no es meramente descriptiva: determina el interés asegurable de cada sujeto (el propietario no ocupante suele asegurar solo el continente; el inquilino, solo el contenido y su responsabilidad civil) y condiciona la correcta fijación de la suma asegurada a efectos de la regla proporcional del artículo 30 LCS, como se desarrolla en el capítulo 15."),

    B.h2("1.5. Condiciones generales, particulares y especiales: la distinción entre cláusulas delimitadoras y limitativas"),
    B.p("El artículo 3 LCS es, junto con el artículo 20, el precepto más invocado en la litigación sobre seguros de hogar. Su tenor es el siguiente:"),
    B.legalBox("Art. 3 LCS", "Las condiciones generales, que en ningún caso podrán tener carácter lesivo para los asegurados, habrán de incluirse por el asegurador en la proposición de seguro si la hubiere y necesariamente en la póliza de contrato o en un documento complementario, que se suscribirá por el asegurado y al que se entregará copia del mismo. Las condiciones generales y particulares se redactarán de forma clara y precisa. Se destacarán de modo especial las cláusulas limitativas de los derechos de los asegurados, que deberán ser específicamente aceptadas por escrito. [...] Declarada por el Tribunal Supremo la nulidad de alguna de las cláusulas de las condiciones generales de un contrato, la Administración Pública competente obligará a los aseguradores a modificar las cláusulas idénticas contenidas en sus pólizas."),
    B.p("De este precepto derivan dos regímenes jurídicos distintos que el profesional debe aprender a diferenciar en cada cláusula controvertida:"),
    B.bullet([B.bold("Cláusulas delimitadoras del riesgo: "), B.run("concretan el objeto del contrato, fijando qué riesgos, en caso de producirse, hacen surgir el derecho a la prestación. Basta su inclusión en condiciones generales aceptadas de forma genérica al perfeccionarse el contrato, sin necesidad de firma o aceptación específica adicional.")]),
    B.bullet([B.bold("Cláusulas limitativas de los derechos del asegurado: "), B.run("una vez nacido el derecho a la prestación, lo restringen, condicionan o modifican. Exigen, bajo pena de inoponibilidad al asegurado, que estén destacadas de modo especial y que sean específicamente aceptadas por escrito (doble requisito: destacado formal + firma o aceptación expresa distinta de la firma general de la póliza).")]),
    B.p("La distinción, aparentemente sencilla en la teoría, resulta enormemente controvertida en la práctica, y ha generado una jurisprudencia extensa y matizada. La sentencia de referencia —citada de forma constante por la Sala Primera hasta la actualidad— es la STS (Pleno) 853/2006, de 11 de septiembre, cuya doctrina resume con fidelidad la reciente STS 3996/2023, de 3 de octubre (ECLI:ES:TS:2023:3996, ponente Seoane Spiegelberg):"),
    B.jurisBox("STS 3996/2023, de 3 de octubre (ECLI:ES:TS:2023:3996)", "«Son delimitadoras las condiciones mediante las cuales se concreta el objeto del contrato, fijando qué riesgos, en caso de producirse, por constituir el objeto del seguro, hacen surgir en el asegurado el derecho a la prestación, y en la aseguradora el recíproco deber de atenderla [...]. Un criterio utilizado para determinar la naturaleza de ciertas cláusulas para darles el tratamiento de limitativas, es referirlo al contenido natural del contrato; esto es, del alcance típico o usual que corresponde a su objeto con arreglo a lo dispuesto en la ley o en la práctica aseguradora (SSTS 273/2016, de 22 de abril, 541/2016, de 14 de septiembre y 147/2017, de 2 de marzo). En este sentido, se atribuye la condición de limitativa a la cláusula sorpresiva que se aparta de dicho contenido ordinario (STS 58/2019, de 29 de enero, 661/2019, de 12 de diciembre y 87/2021, de 17 de febrero). Las consecuencias de dicha diferenciación devienen fundamentales, dado que las cláusulas delimitadoras [...] quedan sometidas al régimen de aceptación genérica, sin la necesidad de la observancia de los requisitos de incorporación que se exige a las limitativas.»"),
    B.p("La misma doctrina se reitera, aplicada a un seguro multirriesgo de comercio pero plenamente extrapolable al de hogar, en la STS 1751/2025, de 21 de abril (ECLI:ES:TS:2025:1751), que insiste en el criterio de la «cláusula sorpresiva» como indicio decisivo: una condición general que, aunque formalmente delimite el riesgo, se aparta del contenido natural o usual de la modalidad contratada y frustra las expectativas razonables del asegurado, recibe en la práctica el tratamiento —y las garantías formales— propio de las cláusulas limitativas."),
    B.p("La aplicación práctica de esta doctrina al seguro de hogar puede ilustrarse con la STS 2233/2020, de 6 de julio (ECLI:ES:TS:2020:2233, ponente Seoane Spiegelberg), referida precisamente a una póliza multirriesgo del hogar:"),
    B.jurisBox("STS 2233/2020, de 6 de julio (ECLI:ES:TS:2020:2233)", "Contrato de seguro en la modalidad multirriesgo del hogar. Daños producidos en prendas de vestir. La cláusula que valora estas prendas por su «valor real» —y no por su valor de reposición o coste de sustitución— se califica como cláusula limitativa que no reúne los requisitos formales del artículo 3 LCS, por lo que resulta inoponible al asegurado."),
    B.p("De esta línea jurisprudencial se extrae una regla práctica de gran utilidad: cuando una cláusula, aunque formalmente incluida en el capítulo de «definiciones» o de «cobertura», tiene el efecto real de reducir lo que el asegurado razonablemente esperaba obtener contratando ese tipo de seguro (por ejemplo, valorar el contenido por su valor real y no de reposición, limitar cuantitativamente una cobertura de defensa jurídica anunciada como «ilimitada», o excluir de facto un riesgo típico del ramo), los tribunales tienden a reconducirla al régimen de las limitativas, con independencia de su ubicación formal en la póliza."),

    B.h3("1.5.1. El principio de transparencia como fundamento común"),
    B.p("La STS 732/2017, de 2 de marzo (ECLI:ES:TS:2017:732, ponente Orduña Moreno), añade una capa adicional de análisis especialmente útil para el profesional que revisa una póliza controvertida: el «principio de transparencia», que subyace a todo el artículo 3 LCS y que «opera con especial intensidad respecto de las cláusulas introductorias o particulares». Cuando una cláusula general introduce, so capa de definición, un «insólito plus» restrictivo no anunciado en las condiciones particulares ni en la información precontractual, la sala aprecia su carácter sorpresivo y, por ello, limitativo, con independencia de la etiqueta que le haya dado el redactor de la póliza."),

    B.h2("1.6. Las cláusulas lesivas: la frontera de la nulidad"),
    B.p("El artículo 3 LCS distingue todavía una tercera categoría, más severa: las cláusulas lesivas, que son directamente nulas y no admiten subsanación por aceptación expresa, a diferencia de las limitativas. Son lesivas aquellas cláusulas que producen un desequilibrio importante e injustificado en perjuicio del asegurado, en contra de las exigencias de la buena fe; su tratamiento se completa, cuando el tomador es consumidor, con el régimen de cláusulas abusivas del TRLGDCU y de la LCGC, que se desarrolla con detalle en el capítulo 21 de esta obra."),

    B.h2("1.7. Ficha para el profesional"),
    B.fichaBox("Puntos de control al analizar una póliza de hogar", B.AZUL, [
      "Identificar primero si la cláusula controvertida define el riesgo (delimitadora) o restringe un derecho ya nacido (limitativa): la consecuencia práctica —oponibilidad o inoponibilidad al asegurado— depende enteramente de esta calificación.",
      "Verificar, ante toda cláusula limitativa, el doble requisito formal del art. 3 LCS: destacado tipográfico especial y aceptación específica por escrito, distinta de la firma genérica de la póliza (véase el criterio de la STS 3996/2023 sobre epígrafes en mayúscula y recuadrados).",
      "Aplicar el test de la «cláusula sorpresiva»: comparar el contenido de la cláusula con el alcance típico o usual del ramo contratado, conforme a la práctica aseguradora (SSTS 273/2016, 541/2016, 147/2017).",
      "Distinguir la cláusula limitativa (subsanable por aceptación expresa) de la lesiva (nula de pleno derecho, no subsanable).",
      "Cuando el tomador sea consumidor, doblar el análisis del art. 3 LCS con el control de incorporación y de contenido de la LCGC y el TRLGDCU (capítulo 21).",
    ]),

    B.h2("1.8. Ficha para el asegurado"),
    B.fichaBox("Qué debe comprobar el asegurado al recibir su póliza", "8A5A00", [
      "Lea las condiciones particulares y compárelas con lo que le explicó el mediador o la web de contratación: si algo relevante no aparece destacado en negrita o en un apartado propio con su firma, es indicio de que podría tratarse de una cláusula limitativa mal incorporada.",
      "Compruebe cómo se valoran los bienes del contenido en caso de siniestro (valor real, valor de reposición o valor de nuevo) y las sumas aseguradas de continente y contenido por separado.",
      "Revise los límites específicos para joyas, dinero en efectivo, equipos electrónicos y objetos de valor: suelen ser sublímites dentro de la suma general del contenido.",
      "Conserve siempre copia firmada de las condiciones particulares y generales: es el documento que, conforme al art. 3 LCS, la aseguradora debe entregarle en el momento de la contratación.",
    ]),

    B.h2("1.9. Checklist: cómo leer una póliza de hogar en diez puntos"),
    B.bullet("1. Tomador, asegurado y beneficiario: ¿coinciden? ¿Es la vivienda habitual, segunda residencia o vivienda arrendada?"),
    B.bullet("2. Continente y contenido: sumas aseguradas independientes y su relación con el valor real del inmueble y los bienes."),
    B.bullet("3. Franquicias aplicables por tipo de garantía."),
    B.bullet("4. Sublímites por garantía (joyas, dinero, equipos electrónicos, objetos de arte)."),
    B.bullet("5. Exclusiones generales y particulares (capítulo 12)."),
    B.bullet("6. Cobertura de responsabilidad civil de cabeza de familia: límite por siniestro y por anualidad."),
    B.bullet("7. Cobertura de defensa jurídica: cuantía y libre elección de abogado y procurador."),
    B.bullet("8. Plazo de comunicación del siniestro pactado en póliza (nunca puede ser inferior a los 7 días del art. 16 LCS, pero sí superior)."),
    B.bullet("9. Cláusulas destacadas en negrita, mayúsculas o recuadro con firma o aceptación específica separada."),
    B.bullet("10. Fecha de efecto, forma de pago de la prima y consecuencias del impago (art. 15 LCS)."),
  ];
}

module.exports = { capitulo01 };
