const B = require("./build");

function capitulo10() {
  return [
    B.chapterHeading(10, "Fenómenos atmosféricos y riesgos extraordinarios: el Consorcio de Compensación de Seguros"),

    B.sumario([
      "10.1. Riesgos ordinarios y riesgos extraordinarios: dos regímenes distintos",
      "10.2. Fenómenos atmosféricos ordinarios en el clausulado privado",
      "10.3. El Consorcio de Compensación de Seguros: naturaleza y ámbito",
      "10.4. Los acontecimientos extraordinarios legalmente tipificados",
      "10.4.1. La definición reglamentaria de inundación extraordinaria y su frontera con el seguro privado",
      "10.4.2. El control judicial de la calificación del evento",
      "10.5. Presupuestos y límites de la cobertura del Consorcio",
      "10.6. Riesgos expresamente excluidos de la cobertura del Consorcio",
      "10.7. Procedimiento de reclamación ante el Consorcio",
      "10.7.1. Los umbrales de intensidad importados al clausulado privado: la cláusula de los 40 litros",
      "10.8. Ficha para el profesional",
      "10.9. Ficha para el asegurado",
      "10.10. Checklist: seguro privado o Consorcio",
    ]),
    B.spacer(160),
    B.abstractBlock(
      "El capítulo delimita la frontera, con frecuencia mal comprendida por el asegurado medio, entre los fenómenos atmosféricos cubiertos por el clausulado ordinario de la póliza de hogar y los acontecimientos extraordinarios cuya cobertura corresponde, por mandato legal, al Consorcio de Compensación de Seguros (RDL 7/2004 y RD 300/2004). Se examina con detalle la definición reglamentaria de inundación extraordinaria y sus exclusiones —determinantes del deslinde práctico entre Consorcio y aseguradora privada—, el control judicial de la calificación del evento como concepto jurídico indeterminado, y la práctica, censurada por la Sala Primera, de importar al clausulado privado los umbrales de intensidad propios de lo catastrófico.",
      "Consorcio de Compensación de Seguros, riesgos extraordinarios, inundación extraordinaria, tempestad ciclónica atípica, recargo obligatorio, concepto jurídico indeterminado",
      "This chapter draws the often misunderstood line between ordinary weather perils covered by standard homeowners' policy wording and extraordinary events whose coverage is, by statutory mandate, assumed by the Spanish Insurance Compensation Consortium. It examines in detail the regulatory definition of extraordinary flooding and its exclusions —which determine the practical boundary between the Consortium and the private insurer—, the judicial review of the event's classification as an indeterminate legal concept, and the practice, censured by the Supreme Court, of importing catastrophe-level intensity thresholds into private policy wording.",
      "Insurance Compensation Consortium, extraordinary risks, extraordinary flooding, atypical cyclonic storm, mandatory surcharge, indeterminate legal concept"
    ),
    B.spacer(200),

    B.h2("10.1. Riesgos ordinarios y riesgos extraordinarios: dos regímenes distintos"),
    B.p(["El sistema español de cobertura de catástrofes se articula sobre una summa divisio esencial que el profesional debe explicar con claridad a cualquier asegurado: los fenómenos atmosféricos ordinarios (viento, lluvia y pedrisco de intensidad habitual) se cubren, cuando la póliza lo prevea, por la propia aseguradora privada conforme a sus condiciones generales; los acontecimientos extraordinarios legalmente tipificados —inundación extraordinaria, terremoto, tempestad ciclónica atípica, entre otros— quedan excluidos, con carácter general, del seguro privado y son asumidos, en régimen de compensación, por el Consorcio de Compensación de Seguros (CCS), entidad pública empresarial adscrita al Ministerio de Economía", B.fn("El sistema dual español —aseguramiento privado de riesgos ordinarios y cobertura pública complementaria de riesgos catastróficos mediante recargo obligatorio— es una de las señas de identidad del ordenamiento asegurador español, sin equivalente exacto en otros ordenamientos de nuestro entorno; sobre su fundamento y funcionamiento, vid. VEIGA COPO, A. B., Tratado del Contrato de Seguro, op. cit., tomo dedicado al Consorcio de Compensación de Seguros."), "."]),

    B.h2("10.2. Fenómenos atmosféricos ordinarios en el clausulado privado"),
    B.p("Las condiciones generales de las pólizas de hogar suelen incorporar una garantía de «fenómenos atmosféricos» que cubre daños causados por viento, lluvia, pedrisco o nieve de intensidad ordinaria, normalmente sujeta a umbrales técnicos de intensidad (por ejemplo, viento con rachas superiores a un determinado número de kilómetros por hora, medido por estaciones meteorológicas de referencia) por debajo de los cuales el daño se reconduce a la garantía general de daños al continente y por encima de los cuales, si alcanza la calificación de «extraordinario» conforme al RDL 7/2004, la cobertura corresponde al Consorcio y no a la aseguradora privada."),

    B.h2("10.3. El Consorcio de Compensación de Seguros: naturaleza y ámbito"),
    B.p("El régimen legal del Consorcio se contiene en el Real Decreto Legislativo 7/2004, de 29 de octubre, por el que se aprueba el texto refundido del Estatuto Legal del Consorcio de Compensación de Seguros, desarrollado reglamentariamente por el Real Decreto 300/2004. Su función, en materia de riesgos extraordinarios sobre bienes, es indemnizar, en régimen de compensación (no de seguro en sentido estricto), las pérdidas derivadas de acontecimientos extraordinarios:"),
    B.legalBox("Art. 6.1 del Estatuto Legal del CCS (RDL 7/2004)", "El Consorcio, en materia de riesgos extraordinarios, tendrá por objeto indemnizar, en la forma establecida en este Estatuto Legal, en régimen de compensación, las pérdidas derivadas de acontecimientos extraordinarios acaecidos en España y que afecten a riesgos en ella situados. [...] A estos efectos, serán pérdidas los daños directos en las personas y en los bienes, así como [...] las pérdidas pecuniarias como consecuencia de aquéllos."),
    B.p("La cobertura del Consorcio no es, técnicamente, un seguro adicional que el asegurado contrate de forma independiente, sino un régimen de compensación financiado mediante un recargo obligatorio que se aplica automáticamente a determinadas pólizas de seguro de daños —entre ellas, las de hogar— y cuya gestión corresponde íntegramente al propio Consorcio, al margen de la aseguradora privada."),

    B.h2("10.4. Los acontecimientos extraordinarios legalmente tipificados"),
    B.p("El artículo 6.1 del Estatuto Legal enumera con carácter tasado los acontecimientos que reciben la calificación de «extraordinarios» a efectos de esta cobertura:"),
    B.legalBox("Art. 6.1.a)-c) del Estatuto Legal del CCS (RDL 7/2004)", "Se entenderán [...] por acontecimientos extraordinarios: a) Los siguientes fenómenos de la naturaleza: terremotos y maremotos, las inundaciones extraordinarias, las erupciones volcánicas, la tempestad ciclónica atípica y las caídas de cuerpos siderales y aerolitos. b) Los ocasionados violentamente como consecuencia de terrorismo, rebelión, sedición, motín y tumulto popular. c) Hechos o actuaciones de las Fuerzas Armadas o de las Fuerzas y Cuerpos de Seguridad en tiempo de paz."),
    B.p("La calificación técnica de un episodio concreto como «inundación extraordinaria» o «tempestad ciclónica atípica» —a diferencia de una lluvia o un viento intensos pero ordinarios— corresponde en primera instancia al propio Consorcio, con arreglo a criterios técnicos e hidrológicos o meteorológicos objetivos, lo que en la práctica exige al profesional verificar, ante cada episodio de fuertes lluvias o viento, si el Consorcio ha calificado el evento como extraordinario para la zona y fecha del siniestro, dato habitualmente publicado por el propio organismo. Ahora bien, esa calificación administrativa ni agota el concepto legal ni resulta inmune al control de los tribunales, según se expone en los dos apartados siguientes."),

    B.h3("10.4.1. La definición reglamentaria de inundación extraordinaria y su frontera con el seguro privado"),
    B.p("El desarrollo reglamentario del Estatuto Legal precisa qué debe entenderse por cada uno de los acontecimientos extraordinarios. La definición de «inundación extraordinaria» es, con diferencia, la de mayor trascendencia práctica en el ramo de hogar, y merece transcripción literal por la precisión de sus exclusiones finales:"),
    B.legalBox("Art. 2.1.c) del Reglamento del seguro de riesgos extraordinarios (RD 300/2004)", "Inundación extraordinaria: el anegamiento del terreno producido por la acción directa de las aguas de lluvia, las procedentes de deshielo o las de los lagos que tengan salida natural, de los ríos o rías o de cursos naturales de agua en superficie, cuando éstos se desbordan de sus cauces normales, así como los embates de mar en las costas. No se entenderá por tal la producida por aguas procedentes de presas, canales, alcantarillas, colectores y otros cauces subterráneos, construidos por el hombre, al reventarse, romperse o averiarse por hechos que no correspondan a riesgos de carácter extraordinario amparados por el Consorcio de Compensación de Seguros, ni la lluvia caída directamente sobre el riesgo asegurado, o la recogida por su cubierta o azotea, su red de desagüe o sus patios."),
    B.p(["La lectura atenta de este precepto suministra el criterio de deslinde más útil de todo el capítulo, y conviene retenerlo con precisión porque decide, en la inmensa mayoría de los siniestros de lluvias intensas, a quién debe dirigirse la reclamación", B.fn("La frontera no se traza, como suele creerse, por la intensidad pluviométrica del episodio, sino por el mecanismo físico del daño: el Consorcio cubre el anegamiento del terreno —incluido el causado por la acción directa del agua de lluvia sobre él— y el desbordamiento de cauces naturales, mientras que la lluvia que penetra por la cubierta, la azotea, la red de desagüe o los patios del propio inmueble queda expresamente fuera de su ámbito y se reconduce, si existe cobertura, al clausulado privado. De ahí que un mismo episodio meteorológico pueda generar simultáneamente daños a cargo del Consorcio y daños a cargo de la aseguradora privada en un mismo edificio."), ":"]),
    B.bullet([B.bold("Corresponde al Consorcio: "), B.run("el anegamiento del terreno por acción directa de las aguas de lluvia, deshielo o lagos con salida natural; el desbordamiento de ríos, rías y cursos naturales de agua en superficie; y los embates de mar en las costas.")]),
    B.bullet([B.bold("Queda fuera del Consorcio (y, por tanto, se reconduce al seguro privado si este lo cubre): "), B.run("la lluvia caída directamente sobre el riesgo asegurado o recogida por su cubierta, azotea, red de desagüe o patios; y el agua procedente de presas, canales, alcantarillas, colectores y demás cauces construidos por el hombre que revienten, se rompan o se averíen por causas no extraordinarias.")]),
    B.p("La consecuencia práctica es de primer orden y con frecuencia se pasa por alto: en un episodio de lluvias torrenciales, los daños causados por el agua que anegó la planta baja desde la calle son cuestión del Consorcio, mientras que los daños causados en la misma vivienda por las filtraciones a través de la cubierta o por el desbordamiento del sumidero de un patio interior son cuestión de la aseguradora privada —y se reconducen, en su caso, al régimen de la garantía de daños por agua estudiada en el capítulo 8, con toda su casuística sobre vicio, desgaste y falta de mantenimiento—. Un mismo siniestro puede exigir, por tanto, dos reclamaciones simultáneas ante interlocutores distintos, y el error en la elección del destinatario es una causa frecuente de pérdida de tiempo cuando no de prescripción."),

    B.h3("10.4.2. El control judicial de la calificación del evento"),
    B.p(["Aunque la calificación técnica inicial corresponda al Consorcio, la determinación de si un concreto episodio encaja o no en el concepto legal de acontecimiento extraordinario constituye la interpretación de un concepto jurídico indeterminado y, como tal, queda sometida al control pleno de los tribunales, que no están vinculados por el criterio administrativo. Así lo declaró la Sala Primera en un supuesto de lluvias torrenciales en el que el Consorcio negaba la existencia de «inundación» por tratarse de un inmueble situado en ladera"]),
    B.jurisBox("STS, Sala de lo Civil, de 31 de octubre de 2007 (ROJ: STS 6939/2007; ECLI:ES:TS:2007:6939; MP: García Varela)", "«[R]espetando la potestad reglamentaria estatal, han de ser siempre los Tribunales, ejerciendo la exclusiva potestad de juzgar, los que han de decidir si la interpretación dada por la Administración al concepto jurídico indeterminado empleado por la norma con rango de ley, se adapta a ésta y agota su contenido o, por el contrario, la contradice por limitar expresamente su ámbito, excluyendo una parcela de la realidad a través del Reglamento, cuando dicha realidad está abarcada por la Ley.»"),
    B.p(["La sentencia rechazó, en el caso concreto, la distinción entre «inundación» y «saturación» del terreno que se había empleado para denegar la cobertura, por su «nimiedad conceptual» y por apoyarse en una diferencia semántica no apropiada. Conviene precisar, no obstante, que la resolución aplicó la normativa entonces vigente —la Ley de 16 de diciembre de 1954, de creación del Consorcio, y el Reglamento aprobado por Real Decreto 2022/1986—, hoy sustituidas por el RDL 7/2004 y el RD 300/2004 transcrito en el apartado anterior", B.fn("La sustitución normativa no priva de vigencia a la doctrina sobre el control judicial del concepto jurídico indeterminado, que es una doctrina de alcance general sobre la relación entre ley y reglamento y sobre los límites de la interpretación administrativa, y no una regla dependiente del concreto texto reglamentario aplicado. Sí obliga, en cambio, a construir hoy el argumento sobre la definición vigente del art. 2.1.c) del RD 300/2004, sensiblemente más detallada que la de 1986, y a no reproducir sin más los pasajes de la sentencia referidos al texto derogado."), ". Lo que conserva plena vigencia es la regla de fondo: el asegurado a quien se deniega la cobertura por una calificación técnica desfavorable del episodio no se enfrenta a una decisión inatacable, sino a un criterio administrativo revisable en sede judicial."]),

    B.h2("10.5. Presupuestos y límites de la cobertura del Consorcio"),
    B.p("La obligación del Consorcio de indemnizar un siniestro derivado de un acontecimiento extraordinario está sujeta a presupuestos precisos que conviene verificar sistemáticamente:"),
    B.legalBox("Art. 8.1 y 8.2 del Estatuto Legal del CCS (RDL 7/2004)", "El Consorcio estará obligado a satisfacer las indemnizaciones derivadas de siniestros producidos por acontecimientos extraordinarios a los asegurados que hayan satisfecho los correspondientes recargos en favor de aquel y se encuentren en alguna de las situaciones siguientes: a) Que el riesgo extraordinario cubierto por el Consorcio no esté amparado por póliza de seguro. b) Que, aun estando amparado por póliza de seguro, las obligaciones de la entidad aseguradora no pudieran ser cumplidas por haber sido declarada judicialmente en concurso [...]. La obligación del Consorcio amparará necesaria y exclusivamente a las mismas personas o bienes y por las mismas sumas aseguradas que se hayan establecido en las pólizas de seguro [...]. Esta obligación se limitará a las indemnizaciones que proceda abonar conforme a la ley española de contrato de seguro."),
    B.bullet([B.bold("Existencia de póliza de seguro de daños vigente: "), B.run("el Consorcio actúa, con carácter general, como complemento de una póliza privada de daños que incluya el recargo obligatorio; un inmueble sin ningún seguro de daños contratado no queda, con carácter general, amparado por el Consorcio para riesgos extraordinarios sobre bienes.")]),
    B.bullet([B.bold("Pago del recargo: "), B.run("el recargo se incorpora automáticamente al recibo de la póliza privada por mandato legal, sin que el tomador pueda, en la práctica, excluirlo respecto de los riesgos y bienes amparados por la póliza.")]),
    B.bullet([B.bold("Límite cuantitativo: "), B.run("la indemnización del Consorcio se limita a las mismas personas, bienes y sumas aseguradas que figuren en la póliza privada subyacente, sin que pueda exceder dichos límites.")]),

    B.h2("10.6. Riesgos expresamente excluidos de la cobertura del Consorcio"),
    B.p("El artículo 6.3 del Estatuto Legal excluye expresamente determinados supuestos, de particular relevancia práctica en el ramo de hogar:"),
    B.bullet([B.bold("Vicio o defecto propio de la cosa asegurada: "), B.run("un daño causado por defectos constructivos previos, aunque coincida temporalmente con un episodio de lluvias intensas, no queda amparado por esta vía.")]),
    B.bullet([B.bold("Mera acción del tiempo o agentes atmosféricos ordinarios: "), B.run("distintos de los fenómenos de la naturaleza expresamente tipificados como extraordinarios, lo que reconduce estos daños a la cobertura ordinaria de la póliza privada, si existe.")]),
    B.bullet([B.bold("Siniestros no indemnizables conforme a la LCS: "), B.run("el Consorcio no amplía el régimen causal de la LCS; si un daño no sería indemnizable por un asegurador privado conforme a la Ley (por ejemplo, por dolo del asegurado), tampoco lo es por el Consorcio.")]),

    B.h2("10.7. Procedimiento de reclamación ante el Consorcio"),
    B.p("Cuando un siniestro se atribuye a un acontecimiento extraordinario, el asegurado debe dirigir su reclamación directamente al Consorcio de Compensación de Seguros, no a su aseguradora privada, sin perjuicio de que esta última pueda —y en la práctica suela— colaborar en la tramitación inicial del expediente. El Consorcio dispone de su propio cuerpo de peritos y de un procedimiento de valoración específico, regulado reglamentariamente, cuyos plazos y trámites, aunque inspirados en el régimen general de la LCS, presentan especialidades administrativas propias que exceden el objeto de esta obra y que conviene verificar en cada caso en la normativa reglamentaria y en la información oficial del propio organismo."),

    B.h3("10.7.1. Los umbrales de intensidad importados al clausulado privado: la cláusula de los 40 litros"),
    B.p("Existe una práctica de redacción, muy extendida en el ramo de hogar, que merece un tratamiento específico por su elevada litigiosidad: la aseguradora privada, al definir en sus condiciones generales qué considera «lluvia anormal» a efectos de su propia garantía de fenómenos atmosféricos, importa los umbrales técnicos de intensidad que el Reglamento del Consorcio emplea para definir la tempestad ciclónica atípica —señaladamente, los 40 litros por metro cuadrado y hora y los 84 kilómetros por hora de viento del art. 2.1.e) del RD 300/2004—. El efecto de esa importación es demoledor para el asegurado: si solo se cubre la lluvia que supere el umbral de lo extraordinario, y lo extraordinario corresponde por ley al Consorcio, la garantía privada de lluvia queda materialmente vacía de contenido, pues opera únicamente en un ámbito en el que quien responde es otro."),
    B.p("La Sala Primera ha resuelto expresamente esta cuestión, y lo ha hecho en un supuesto de póliza multirriesgo familia-hogar, calificando la cláusula como limitativa e inoponible por no haber sido destacada ni específicamente aceptada:"),
    B.jurisBox("STS, Sala de lo Civil, de 22 de marzo de 2021 (ROJ: STS 1081/2021; ECLI:ES:TS:2021:1081; MP: Arroyo Fiestas)", "«[N]os encontramos ante una cláusula limitativa en cuanto restringe o modifica el derecho del asegurado, generando confusión en el mismo, hasta el punto de que razonablemente podría creer que estaba acogido a la cobertura del riesgo por lluvia, cuando de forma poco transparente se incluía una condición especial en la página 14 de la póliza, que alteraba el contenido usual de este tipo de contratos, alterando las expectativas razonables del asegurado, confiado en el texto de las condiciones particulares de la póliza. Este tipo de cláusula que calificamos como limitativa, restringe de forma esencial, inesperada y exorbitante el objeto del seguro, la cual no respeta el dictado del art. 3 de la LCS, pues no fue destacada ni aceptada expresamente.»"),
    B.p(["El razonamiento de la sentencia es un ejemplo de manual de la metodología expuesta en los capítulos 1 y 5: las condiciones particulares anunciaban la cobertura de los daños por lluvia, viento, pedrisco y nieve con sumas aseguradas concretas y sin exclusión alguna, mientras que una condición especial situada en la página catorce del documento restringía esa cobertura a los episodios que superasen umbrales cuantitativos propios de lo catastrófico. La Sala aprecia el carácter sorpresivo por el contraste entre lo anunciado y lo efectivamente cubierto, y no por la mera ubicación de la cláusula", B.fn("El caso ilustra con particular nitidez la utilidad del criterio del «contenido natural del contrato» y de las «expectativas razonables» del asegurado, ya estudiados en el capítulo 1: la cobertura de daños por lluvia constituye prestación natural de una póliza multirriesgo de hogar que la anuncia en sus condiciones particulares, de modo que la restricción preestablecida que la vacía de contenido efectivo exige la garantía adicional de conocimiento propia del régimen de las cláusulas limitativas. Es también un ejemplo de cómo una misma cifra —los 40 litros por metro cuadrado y hora— cumple una función legítima en la norma reglamentaria que delimita la competencia del Consorcio y una función abusiva cuando se traslada, sin advertencia destacada, al clausulado de una garantía privada."), ". Se trata, en definitiva, de una de las resoluciones de mayor rendimiento argumental de todo el ramo, y de cita obligada siempre que una aseguradora deniegue un siniestro de lluvia o viento invocando umbrales de intensidad no destacados ni firmados."]),
    B.fichaBox("Puntos de control ante un siniestro atmosférico de entidad", B.AZUL, [
      "Verificar si el Consorcio ha calificado oficialmente el episodio como «acontecimiento extraordinario» para la zona y fecha del siniestro, antes de dirigir la reclamación a la aseguradora privada o al propio Consorcio.",
      "Identificar el mecanismo físico del daño, y no solo la intensidad del episodio: anegamiento del terreno y desbordamiento de cauces naturales son cuestión del Consorcio; la lluvia recogida por cubierta, azotea, red de desagüe o patios queda fuera de su ámbito (art. 2.1.c) RD 300/2004) y se reconduce al seguro privado.",
      "Valorar si un mismo episodio ha generado daños de ambas clases en el mismo inmueble, en cuyo caso procede una doble reclamación simultánea ante Consorcio y aseguradora privada.",
      "Si la calificación técnica del Consorcio es desfavorable, recordar que se trata de la interpretación de un concepto jurídico indeterminado sometida al control pleno de los tribunales (STS 6939/2007, ROJ: STS 6939/2007), y no de una decisión inatacable.",
      "Ante la denegación de un siniestro de lluvia o viento por no alcanzarse un umbral de intensidad fijado en condiciones generales, examinar si dicho umbral fue destacado y específicamente aceptado: de no serlo, es cláusula limitativa inoponible (STS 1081/2021, ROJ: STS 1081/2021).",
      "Comprobar que la póliza de hogar del cliente está vigente y al corriente de pago (incluido el recargo del Consorcio) en la fecha del siniestro.",
      "Distinguir con prueba pericial entre el daño atribuible al fenómeno extraordinario y el atribuible a un vicio o defecto constructivo preexistente, expresamente excluido de la cobertura del Consorcio.",
      "Tener presente que la indemnización del Consorcio se limita a los mismos bienes y sumas aseguradas de la póliza privada subyacente: revisar la suficiencia de dichas sumas es tan relevante como en el seguro ordinario.",
    ]),

    B.h2("10.9. Ficha para el asegurado"),
    B.fichaBox("Qué debe saber sobre la cobertura de catástrofes", "8A5A00", [
      "Si su vivienda sufre daños por una inundación, un terremoto o un temporal de gran intensidad, es posible que la reclamación deba dirigirse al Consorcio de Compensación de Seguros y no (solo) a su aseguradora habitual.",
      "El recargo del Consorcio ya está incluido en el recibo de su seguro de hogar: no es una contratación adicional ni puede excluirla si su póliza cubre los bienes correspondientes.",
      "Guarde el recibo de su póliza y compruebe que está al corriente de pago: es requisito para la cobertura del Consorcio.",
      "La indemnización del Consorcio nunca superará la suma asegurada de su propia póliza: si su vivienda está infraasegurada, esa limitación también le afectará en un siniestro extraordinario.",
      "No todo el daño de un mismo temporal corre a cargo del mismo pagador: el agua que entró desde la calle anegando el terreno suele ser cuestión del Consorcio, mientras que las filtraciones por el tejado o el desbordamiento del sumidero de un patio son cuestión de su aseguradora. Puede ser necesario reclamar a los dos.",
      "Si su aseguradora le deniega un siniestro de lluvia o viento porque «no se alcanzaron los litros o los kilómetros por hora exigidos», compruebe si esa condición estaba destacada y firmada por usted: si no lo estaba, hay jurisprudencia del Tribunal Supremo que la considera inoponible.",
    ]),

    B.h2("10.10. Checklist: seguro privado o Consorcio"),
    B.bullet("1. ¿El fenómeno ha sido calificado oficialmente como acontecimiento extraordinario?"),
    B.bullet("2. ¿Cuál fue el mecanismo físico del daño: anegamiento del terreno y desbordamiento de cauce natural (Consorcio), o lluvia recogida por cubierta, azotea, desagües o patios (seguro privado)?"),
    B.bullet("3. ¿Ha producido el mismo episodio daños de ambas clases, que exijan reclamación simultánea ante los dos interlocutores?"),
    B.bullet("4. ¿La póliza de hogar estaba vigente y al corriente de pago del recargo en la fecha del siniestro?"),
    B.bullet("5. ¿El daño obedece al fenómeno extraordinario o a un vicio/defecto constructivo preexistente?"),
    B.bullet("6. Si la aseguradora invoca un umbral de intensidad (litros por metro cuadrado, kilómetros por hora), ¿figura destacado y específicamente aceptado por escrito?"),
    B.bullet("7. ¿Las sumas aseguradas de la póliza privada son suficientes, dado que limitan también la cobertura del Consorcio?"),
    B.bullet("8. ¿Se ha presentado la reclamación ante el organismo competente (Consorcio o aseguradora privada) según la calificación del riesgo?"),

    B.h2("Bibliografía citada"),
    B.p("VEIGA COPO, A. B., Tratado del Contrato de Seguro, Civitas-Thomson Reuters, Cizur Menor."),
  ];
}

module.exports = { capitulo10 };
