const B = require("./build");

function capitulo15() {
  return [
    B.chapterHeading(15, "Coberturas especiales: joyas, objetos de valor, equipos electrónicos y comunidades de propietarios"),

    B.sumario([
      "11.1. El régimen de sublímites en el seguro de hogar",
      "11.2. Joyas y objetos de valor",
      "11.3. Equipos electrónicos, informáticos y de telefonía",
      "11.4. Obras de arte y colecciones",
      "11.5. El seguro de la comunidad de propietarios y su interacción con la póliza individual",
      "11.5.1. Las acciones subrogatorias de la aseguradora de la comunidad frente al comunero causante del daño",
      "11.6. Nuevos riesgos del hogar: domótica, autoconsumo eléctrico y ciberriesgos domésticos",
      "11.7. Ficha para el profesional",
      "11.8. Ficha para el asegurado",
      "11.9. Checklist: revisión de sublímites y coberturas especiales",
    ]),
    B.spacer(160),
    B.abstractBlock(
      "El capítulo sistematiza las coberturas especiales o adicionales del seguro de hogar —joyas, dinero en efectivo, equipos electrónicos, obras de arte— estructuradas técnicamente como sublímites dentro de la suma asegurada general del contenido, y su calificación como cláusulas delimitadoras o limitativas conforme a la doctrina ya expuesta en los capítulos 1 y 5. Se completa con el estudio de la interacción entre el seguro individual del propietario y el seguro de la comunidad de propietarios en régimen de propiedad horizontal.",
      "sublímites, joyas, objetos de valor, equipos electrónicos, comunidad de propietarios, seguro de comunidad",
      "This chapter systematises the special or additional covers of homeowners' insurance —jewellery, cash, electronic equipment, artwork— structured technically as sub-limits within the overall contents sum insured, and their classification as risk-delimiting or rights-limiting clauses under the doctrine already set out in Chapters 1 and 4. It closes with an examination of the interaction between an individual owner's policy and the homeowners' association's own insurance under the condominium regime.",
      "sub-limits, jewellery, valuables, electronic equipment, condominium insurance"
    ),
    B.spacer(200),

    B.h2("11.1. El régimen de sublímites en el seguro de hogar"),
    B.p(["Como se anticipó en el capítulo 1, la práctica aseguradora somete determinadas categorías de bienes del contenido a sublímites cuantitativos específicos, inferiores a la suma asegurada general del contenido. Técnicamente, un sublímite es una cláusula delimitadora del objeto de la cobertura —concreta hasta qué importe responde la aseguradora respecto de una determinada categoría de bienes—, pero su calificación puede mudar a limitativa, e incluso lesiva, cuando se aparta de forma sorpresiva de las expectativas razonables del asegurado sobre el alcance de su cobertura general", B.fn("La frontera entre el sublímite como mera concreción cuantitativa del riesgo (delimitador) y el sublímite como vaciamiento encubierto de la cobertura general (limitativo o lesivo) es una de las cuestiones más debatidas en la doctrina reciente sobre el art. 3 LCS aplicado a coberturas especiales; cfr. VEIGA COPO, A. B., Condiciones generales y particulares en el contrato de seguro, op. cit."), ", conforme a la metodología de análisis fijada en el capítulo 5."]),

    B.h2("11.2. Joyas y objetos de valor"),
    B.p("El artículo 46 LCS, estudiado en el capítulo 7, excluye de la cobertura estándar de incendio, «salvo pacto expreso en contrario», los valores mobiliarios, billetes de banco, piedras y metales preciosos y objetos artísticos. La práctica aseguradora traduce esta reserva legal en un sublímite específico para joyas y objetos de valor, normalmente fijado como un porcentaje reducido de la suma asegurada general del contenido, que conviene verificar expresamente en las condiciones particulares. Además del límite cuantitativo, es habitual que estas garantías exijan la acreditación reforzada de la preexistencia (facturas, tasaciones, fotografías) y, en ocasiones, la custodia en caja fuerte como condición de cobertura para determinados umbrales de valor —cláusula cuyo carácter limitativo, si no está debidamente destacada y aceptada conforme al art. 3 LCS, puede ser cuestionado con los mismos argumentos ya expuestos en el capítulo 5."),

    B.h2("11.3. Equipos electrónicos, informáticos y de telefonía"),
    B.p("La cobertura de equipos electrónicos plantea una problemática específica derivada de su rápida obsolescencia y depreciación: la distinción, ya analizada en el capítulo 1 a propósito de la STS 2233/2020 (ROJ: STS 2233/2020) sobre prendas de vestir, entre valoración por «valor real» y por «valor de reposición» adquiere aquí especial relevancia económica, dada la disparidad frecuente entre ambos criterios en bienes tecnológicos. El profesional debe verificar con particular atención qué criterio de valoración aplica la póliza a esta categoría de bienes, por ser habitualmente la fuente de mayor discrepancia económica entre la expectativa del asegurado y la oferta de la aseguradora."),

    B.h2("11.4. Obras de arte y colecciones"),
    B.p("Las pólizas de hogar de gama alta incorporan, en ocasiones mediante condiciones especiales específicas, coberturas para obras de arte, antigüedades o colecciones, sujetas normalmente a la aportación de una tasación pericial previa a la contratación (declaración de valor) que, a diferencia del régimen general, puede vincular contractualmente a las partes sobre el valor del bien a efectos de la indemnización, atemperando en la práctica la aplicación de la regla proporcional del infraseguro estudiada en el capítulo 19 respecto de estos bienes concretos, siempre que la declaración de valor haya sido expresamente aceptada por la aseguradora."),

    B.h2("11.5. El seguro de la comunidad de propietarios y su interacción con la póliza individual"),
    B.p(["La Ley de Propiedad Horizontal no impone con carácter general la obligación de asegurar el edificio, pero sí prevé expresamente la posibilidad de que la comunidad, con cargo al fondo de reserva obligatorio, suscriba un contrato de seguro que cubra los daños causados en la finca", B.fn("La ausencia de una obligación legal general de aseguramiento de la comunidad contrasta con la extendidísima práctica de suscribirlo, impulsada tanto por la prudencia de las juntas de propietarios como, en ocasiones, por su previsión expresa en los estatutos de la comunidad; cfr. BATALLER GRAU, J. et al., op. cit., epígrafe sobre seguros en la propiedad horizontal."), ":"]),
    B.legalBox("Art. 9.1.f) LPH (extracto)", "Con cargo al fondo de reserva la comunidad podrá suscribir un contrato de seguro que cubra los daños causados en la finca o bien concluir un contrato de mantenimiento permanente del inmueble y sus instalaciones generales."),
    B.p("Cuando existe seguro de comunidad, su interacción con la póliza individual de cada propietario debe analizarse, como se expuso en el capítulo 8 a propósito de la STS 1227/2025 (ROJ: STS 1227/2025), verificando la identidad de riesgo e interés asegurado en cada caso concreto: la propia sentencia distingue expresamente los supuestos de «coberturas concurrentes de elementos privativos de inmuebles en propiedad horizontal» —en los que resulta más fácil apreciar dicha identidad y, por tanto, aplicar la contribución proporcional del art. 32 LCS— de otros supuestos, como el arrendamiento, en los que el interés asegurado por cada póliza puede ser sustancialmente distinto."),
    B.p(["El seguro de la comunidad de propietarios presenta, además, una complejidad estructural propia, derivada de su naturaleza de póliza mixta o combinada que yuxtapone coberturas de daños en las cosas (incendio, agua, fenómenos atmosféricos) y coberturas de responsabilidad civil y defensa jurídica del patrimonio comunitario", B.fn("Sobre la caracterización del seguro de comunidad como póliza de naturaleza mixta o combinada —seguro de cosas y, a la vez, seguro de deudas—, con un análisis detallado de sus elementos objetivos y subjetivos (asegurador, tomador, asegurado, beneficiario y tercero perjudicado), vid. TAPIA HERMIDA, A. J., «Los seguros de daños de las comunidades de propietarios y las acciones subrogatorias de las aseguradoras: jurisprudencia reciente», Revista de Responsabilidad Civil y Seguro, núm. 84, INESE, 2022; del mismo autor, Guía del Contrato de Seguro, 2.ª ed., Colección Monografías Aranzadi, Aranzadi, Cizur Menor, 2022. Sobre los seguros de daños en las cosas y los seguros de deudas en general, vid. SÁNCHEZ CALERO, F.; SÁNCHEZ-CALERO GUILARTE, J., Instituciones de Derecho Mercantil, vol. II, últimas ediciones."), ". Esta doble naturaleza determina que el propietario, el copropietario, el inquilino y el tercero perjudicado puedan ocupar, según el caso, distintos roles simultáneos —asegurado respecto de un riesgo, tercero respecto de otro— lo que resulta determinante, como se estudia en el epígrafe siguiente, cuando la aseguradora que ha indemnizado a la comunidad pretende repetir contra el comunero causante del daño."]),

    B.h3("11.5.1. Las acciones subrogatorias de la aseguradora de la comunidad frente al comunero causante del daño"),
    B.p(["Uno de los litigios más recurrentes en la práctica de los seguros de comunidad es el ejercicio, por la aseguradora que ha indemnizado los daños en elementos comunes, de la acción subrogatoria del art. 43 LCS contra el copropietario en cuya vivienda o local se originó el siniestro (típicamente, un incendio). La cuestión decisiva —y la de mayor dificultad práctica— es determinar si dicho comunero tiene, a estos efectos, la condición de «asegurado» por la propia póliza de la comunidad —en cuyo caso el art. 43 LCS impide expresamente que el asegurador se subrogue en su perjuicio— o si, por el contrario, debe tratarse como «tercero responsable» frente al cual la subrogación sí procede", B.fn("La complejidad de esta cuestión, se ha señalado, exige combinar un criterio subjetivo (los distintos roles que juegan comunidad y comuneros según sean tomadores, asegurados o terceros) con un criterio objetivo (el contenido exacto de la cobertura contratada en la póliza litigiosa, que puede o no extender la condición de asegurado a los elementos privativos o a la responsabilidad civil individual de cada comunero); cfr. TAPIA HERMIDA, A. J., «Los seguros de daños de las comunidades de propietarios...», op. cit., epígrafe de conclusiones."), ". La Sala Primera del Tribunal Supremo ha resuelto esta cuestión, entre 2021 y 2022, en tres sentencias que conviene leer de forma conjunta por fijar entre todas una regla general y sus excepciones."]),
    B.p("La primera de ellas parte de un supuesto en el que la propia póliza de la comunidad extendía la garantía de responsabilidad civil a «los copropietarios del Edificio Asegurado» por su condición de tales, lo que llevó a excluir la subrogación:"),
    B.jurisBox("STS, Sala de lo Civil, de 21 de julio de 2021 (ROJ: STS 3162/2021; ECLI:ES:TS:2021:3162; MP: Seoane Spiegelberg)", "«[E]l demandado ostentaba la condición de propietario asegurado por el siniestro objeto de cobertura, y la compañía aseguradora no puede ejercitar en perjuicio de asegurado los derechos en que se haya subrogado. [...] No existe ninguna cláusula de exclusión de la cobertura de incendio sobre los elementos comunes, en el caso de que el fuego proceda de un piso o local privativo de un copropietario; que es además cotitular de dichos elementos. De ser ello así, se debería explicitar en la oportuna cláusula por razones de transparencia contractual.»"),
    B.p("La segunda sentencia, dictada pocos meses después sobre una póliza distinta que no extendía la responsabilidad civil individual de los comuneros, fija la regla general en sentido inverso, precisando además el criterio de distinción frente al primer caso:"),
    B.jurisBox("STS, Sala de lo Civil, de 13 de diciembre de 2021 (ROJ: STS 4579/2021; ECLI:ES:TS:2021:4579; MP: Parra Lucán)", "«[A] efectos de la responsabilidad por daños ejercida por vía de subrogación el copropietario no es asegurado sino tercero responsable, salvo que otra cosa resulte de la propia póliza concertada por la comunidad (como sucedía en el caso de la sentencia 557/2021, de 21 de julio).»"),
    B.p("La tercera sentencia, más reciente, confirma y sistematiza esta regla general con su excepción, resolviendo un supuesto de incendio originado en la motocicleta de un comunero estacionada en el garaje comunitario:"),
    B.jurisBox("STS, Sala de lo Civil, de 5 de julio de 2022 (ROJ: STS 2904/2022; ECLI:ES:TS:2022:2904; MP: Vela Torres)", "«[L]a cualidad de tomador del seguro le corresponde a la comunidad de propietarios, ésta tiene también la condición de asegurada respecto de los elementos comunes del inmueble; mientras que los copropietarios únicamente serían asegurados respecto de sus elementos privativos si los mismos fueran objeto de cobertura en la póliza [...]. En consecuencia, como regla general [...] a efectos de la responsabilidad por daños ejercida por vía de subrogación, el copropietario no es asegurado sino tercero responsable, salvo que otra cosa resulte de la propia póliza concertada por la comunidad.»"),
    B.p(["De esta trilogía jurisprudencial se extrae una metodología de análisis clara para el profesional que se enfrenta a una acción subrogatoria —o a la defensa frente a ella— en el ámbito de la comunidad de propietarios: primero, identificar con precisión qué cubre exactamente la póliza de la comunidad respecto de cada comunero (solo los elementos comunes, o también su responsabilidad civil individual o sus elementos privativos); segundo, verificar que la aseguradora reclama exclusivamente los daños en elementos comunes, y no en la vivienda o local privativo del propio demandado, pues la subrogación exige siempre la existencia de un «tercero» distinto del asegurado indemnizado", B.fn("El requisito de la alteridad —que el sujeto contra quien se dirige la acción subrogatoria sea realmente distinto del asegurado indemnizado— constituye, junto con el pago previo de la indemnización, uno de los presupuestos normativos clásicos de la acción del art. 43 LCS, sistematizados con detalle por la jurisprudencia con cita de la STS 699/2013, de 19 de noviembre; vid. TAPIA HERMIDA, A. J., op. cit."), "; y tercero, distinguir con cuidado, cuando concurran pólizas de comunidad y de hogar individual sobre unos mismos daños, cuál es la aseguradora legitimada para reclamar y frente a quién, aplicando en su caso el régimen de subrogación contra el asegurador del comunero responsable conforme al art. 76 LCS."]),

    B.h2("11.6. Nuevos riesgos del hogar: domótica, autoconsumo eléctrico y ciberriesgos domésticos"),
    B.p(["La transformación tecnológica de la vivienda española plantea, con una velocidad muy superior a la de la reforma legislativa, cuestiones de cobertura que ni la LCS ni buena parte del clausulado tradicional resuelven de forma expresa, lo que exige del profesional un ejercicio de encaje analógico particularmente cuidadoso", B.fn("La brecha entre la evolución técnica del riesgo doméstico y la actualización del clausulado estándar es un fenómeno señalado con frecuencia por la doctrina más reciente en seguros de consumo; ante la falta de previsión expresa, el criterio interpretativo aplicable sigue siendo el de la expectativa razonable del asegurado medio y el contenido natural del ramo, ya estudiados en el capítulo 1."), ":"]),
    B.bullet([B.bold("Instalaciones de autoconsumo eléctrico (placas solares) y baterías domésticas: "), B.run("su condición de elementos fijos incorporados a la vivienda permite, en principio, reconducirlos al concepto de continente estudiado en el capítulo 1, pero su elevado valor unitario y su exposición diferenciada a determinados riesgos (fenómenos atmosféricos, sobretensiones) aconsejan verificar si están sujetas a un sublímite propio o exigen declaración expresa al contratar, dado su carácter de circunstancia potencialmente relevante para la valoración del riesgo a efectos del art. 10 LCS (capítulo 4).")]),
    B.bullet([B.bold("Cargadores de vehículo eléctrico: "), B.run("plantean una doble problemática de cobertura (el propio equipo, como contenido o instalación fija, y los daños que su mal funcionamiento pueda causar, reconducibles a la garantía de daños eléctricos del capítulo 7 o a la de responsabilidad civil del capítulo 13) que exige revisar expresamente su tratamiento en condiciones particulares.")]),
    B.bullet([B.bold("Domótica y dispositivos conectados: "), B.run("su valor como contenido está normalmente cubierto por las garantías estándar de incendio, agua o robo, pero los daños derivados específicamente de su mal funcionamiento informático (no físico) plantean una cuestión de encaje más compleja, próxima a los ciberriesgos.")]),
    B.bullet([B.bold("Ciberriesgos domésticos: "), B.run("fraude informático, suplantación de identidad o ataques a la red doméstica son, en la generalidad de las pólizas de hogar españolas actuales, riesgos no cubiertos por defecto, salvo que se haya contratado expresamente una garantía específica de ciberprotección doméstica, cada vez más ofrecida como cobertura opcional autónoma y sujeta a su propio clausulado, ajeno al régimen de las garantías materiales tradicionales estudiadas en esta obra.")]),
    B.bullet([B.bold("Alquiler vacacional y teletrabajo: "), B.run("el uso de la vivienda para alquiler turístico de corta duración o para el desarrollo de una actividad profesional o empresarial puede constituir, si no fue declarado al contratar, una circunstancia relevante para la valoración del riesgo (art. 10 LCS) o una agravación sobrevenida (art. 11 LCS) sujeta al régimen ya estudiado en el capítulo 4, por lo que su comunicación expresa a la aseguradora es una cautela elemental antes de destinar la vivienda a estos usos.")]),
    B.p("La pauta metodológica general ante cualquiera de estos supuestos es la misma que rige el resto de la obra: en ausencia de previsión expresa en la póliza, debe estarse al contenido natural y a la expectativa razonable del asegurado medio del producto contratado (capítulo 1), sin que la mera novedad técnica del riesgo permita presumir ni su cobertura automática ni su exclusión automática."),

    B.h2("11.7. Ficha para el profesional"),
    B.fichaBox("Puntos de control sobre coberturas especiales", B.AZUL, [
      "Verificar la existencia y cuantía de cada sublímite (joyas, dinero, equipos electrónicos, obras de arte) frente a la suma asegurada general del contenido.",
      "Aplicar la metodología del capítulo 5 (incorporación, calificación, requisitos formales, interpretación) a cada sublímite controvertido, con particular atención a su carácter sorpresivo.",
      "En equipos electrónicos, verificar expresamente el criterio de valoración pactado (valor real o de reposición), invocando en su caso la doctrina de la STS 2233/2020 (ROJ: STS 2233/2020).",
      "Ante un siniestro que afecte a elementos comunes y privativos simultáneamente, verificar la existencia de seguro de comunidad y la identidad de riesgo e interés con la póliza individual, conforme a la STS 1227/2025 (ROJ: STS 1227/2025).",
      "Ante una acción subrogatoria de la aseguradora de la comunidad contra un comunero, verificar primero si la póliza extiende a este la condición de asegurado (STS 3162/2021) o si, por regla general, debe tratarse como tercero responsable (SSTS 4579/2021 y 2904/2022), y comprobar que solo se reclaman daños en elementos comunes.",
      "Ante nuevos riesgos del hogar (placas solares, domótica, ciberriesgos, alquiler vacacional), verificar expresamente su tratamiento contractual y, en su caso, su relevancia a efectos del deber de declaración del riesgo del art. 10 LCS.",
    ]),

    B.h2("11.8. Ficha para el asegurado"),
    B.fichaBox("Qué debe revisar sobre sus bienes de especial valor", "8A5A00", [
      "Si posee joyas, dinero en efectivo u objetos de valor por encima del sublímite estándar de su póliza, valore contratar una ampliación específica de esta garantía.",
      "Conserve facturas, tasaciones y fotografías de sus bienes de mayor valor: son la prueba más eficaz en caso de siniestro.",
      "Pregunte a su aseguradora si su comunidad de propietarios tiene contratado un seguro propio y qué cubre exactamente, para evitar solapamientos o lagunas de cobertura.",
      "Si un incendio u otro siniestro se originó en su vivienda o local y causó daños en elementos comunes, sepa que la aseguradora de la comunidad puede reclamarle a usted (o a su propia aseguradora) el importe que haya pagado, salvo que la póliza de la comunidad le reconozca expresamente como asegurado también a estos efectos.",
    ]),

    B.h2("11.9. Checklist: revisión de sublímites y coberturas especiales"),
    B.bullet("1. ¿Qué sublímite tiene pactado para joyas y objetos de valor, y es suficiente para los bienes que realmente posee?"),
    B.bullet("2. ¿Qué sublímite tiene para dinero en efectivo dentro y fuera de la vivienda?"),
    B.bullet("3. ¿Qué criterio de valoración aplica a los equipos electrónicos (valor real o de reposición)?"),
    B.bullet("4. ¿Existe cobertura específica para obras de arte o colecciones, con declaración de valor aceptada por la aseguradora?"),
    B.bullet("5. ¿Existe seguro de la comunidad de propietarios? ¿Qué elementos cubre?"),
    B.bullet("6. ¿Podría existir concurrencia entre la póliza individual y la de la comunidad respecto de algún elemento?"),
    B.bullet("7. Si el siniestro se originó en un elemento privativo y dañó elementos comunes, ¿reclama la aseguradora de la comunidad solo los daños comunes, o también los del propio local o vivienda donde se originó?"),
    B.bullet("8. ¿Extiende la póliza de la comunidad la condición de asegurado al comunero respecto de su responsabilidad civil individual, o lo trata como tercero a estos efectos?"),
    B.bullet("9. ¿Tiene la vivienda placas solares, baterías, cargador de vehículo eléctrico o domótica declarados a la aseguradora?"),
    B.bullet("10. ¿Se destina la vivienda, total o parcialmente, a alquiler turístico o actividad profesional? En tal caso, ¿se ha comunicado a la aseguradora?"),

    B.h2("Bibliografía citada"),
    B.p("BATALLER GRAU, J.; BOQUERA MATARREDONA, J.; OLAVARRÍA IGLESIA, J. (coords.), Comentarios a la Ley de Contrato de Seguro, Tirant lo Blanch, Valencia."),
    B.p("SÁNCHEZ CALERO, F.; SÁNCHEZ-CALERO GUILARTE, J., Instituciones de Derecho Mercantil, vol. II, Aranzadi-Thomson Reuters, Cizur Menor."),
    B.p("TAPIA HERMIDA, A. J., «Los seguros de daños de las comunidades de propietarios y las acciones subrogatorias de las aseguradoras: jurisprudencia reciente», Revista de Responsabilidad Civil y Seguro, núm. 84, INESE, 2022."),
    B.p("TAPIA HERMIDA, A. J., Guía del Contrato de Seguro, 2.ª ed., Colección Monografías Aranzadi, Aranzadi, Cizur Menor, 2022."),
    B.p("VEIGA COPO, A. B., Condiciones generales y particulares en el contrato de seguro, Civitas-Thomson Reuters, Cizur Menor."),
  ];
}

module.exports = { capitulo15 };
